# Generated by Django 6.0.2 on 2026-02-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='puntuacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
