# Generated by Django 6.0.2 on 2026-02-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_content_post_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['titulo'], name='posts_post_titulo_f23bda_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['fecha_creacion'], name='posts_post_fecha_c_52b6f7_idx'),
        ),
    ]
