# Generated by Django 6.0.2 on 2026-02-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_activo_post_posts_post_titulo_f23bda_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Titulo del post', max_length=100),
        ),
    ]
